version: '3'
services:
  openproject:
    image: openproject/openproject:14
    container_name: openproject
    environment:
      - OPENPROJECT_SECRET_KEY_BASE=secret
      - OPENPROJECT_HOST__NAME=localhost:8080
      - OPENPROJECT_HTTPS=false
    ports:
      - "8080:80"
    volumes:
      - ./pgdata:/var/openproject/pgdata
      - ./assets:/var/openproject/assets
    restart: always