version: '3'
services:
  openproject:
    image: openproject/openproject:14
    container_name: openproject
    environment:
      - OPENPROJECT_SECRET_KEY_BASE=secret
      - OPENPROJECT_HOST__NAME=op.localhost
      - OPENPROJECT_HTTPS=true
    volumes:
      - ./pgdata:/var/openproject/pgdata
      - ./assets:/var/openproject/assets
    restart: always
    networks:
      - op_network
  
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/localhost.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - openproject
    networks:
      - op_network

networks:
  op_network:
    driver: bridge